In [1]:
import pandas as pd

In [2]:
import numpy as np

In [5]:
df=pd.read_excel("DB Dota.xlsx")

In [6]:
DF

NameError: name 'DF' is not defined

In [7]:
df

,CARD_FOUR_LAST_DIGITS,CARD_ISSUER_ID,CARD_ISSUER_NAME,CARD_SIX_FIRST_DIGITS,MOV_AMOUNT,MOV_CREATED_DATE,MOV_OPERATION,PAY_COLLECTOR_DOCUMENT,PAY_CURRENCY,PAY_MARKETPLACE,...,CAPTURE_MERCHANT_NUMBER,CAPTURE_MERCHANT_TRX_REFERENCE,PURCHASE_ACQUIRER,PURCHASE_AUTHORIZATION_CODE,PURCHASE_BATCH_ID,PURCHASE_GATEWAY_TRX_ID,PURCHASE_ID,PURCHASE_MERCHANT_NUMBER,PURCHASE_MERCHANT_TRX_REFERENCE,PURCHASE_STATUS
0,7978,1,Visa,588559,2600.00,2022-01-02T23:13:36-04:00,PAYMENT,2.021364e+10,ARS,NONE,...,NaN,NaN,Visa,932099,87.0,3.455300e+10,3.273268e+10,33106584.0,6059.0,approved
1,7976,1,Visa,558766,1709.00,2022-01-02T23:13:35-04:00,PAYMENT,2.034094e+10,ARS,NONE,...,NaN,NaN,Visa,711990,550.0,3.455300e+10,3.273267e+10,32827909.0,5785.0,approved
2,5979,1,Visa,569888,500.00,2022-01-02T23:13:37-04:00,PAYMENT,2.020107e+10,ARS,NONE,...,NaN,NaN,Visa,957843,83.0,3.455300e+10,3.273267e+10,33106584.0,6029.0,approved
3,5977,12433,Visa Ahora,595978,129999.00,2022-01-02T23:12:39-04:00,PAYMENT,3.070881e+10,ARS,NONE,...,48830723.0,9921.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7896,316,BBVA,579555,4410.00,2022-01-02T23:12:38-04:00,PAYMENT,2.742115e+10,ARS,NONE,...,NaN,NaN,Visa,86,339.0,3.455300e+10,3.273268e+10,40326803.0,292.0,approved
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56147,7896,1,Visa,558765,1163.99,2022-01-02T23:50:36-04:00,PAYMENT,3.071451e+10,ARS,MELI,...,NaN,NaN,Visa,37108,550.0,3.455311e+10,3.273276e+10,32827909.0,4914.0,approved
56148,6668,279,Banco Galicia,566869,588.76,2022-01-02T23:51:39-04:00,PAYMENT,3.071531e+10,ARS,NONE,...,NaN,NaN,Visa,153,853.0,3.455311e+10,3.273275e+10,39725643.0,5099.0,approved
56149,9977,1,Visa,558766,2290.00,2022-01-02T23:51:39-04:00,PAYMENT,2.027654e+10,ARS,NONE,...,NaN,NaN,Visa,723921,969.0,3.455311e+10,3.273276e+10,82341942.0,3379.0,approved
56150,58,1,Visa,569888,131.10,2022-01-02T23:51:41-04:00,PAYMENT,2.723785e+10,ARS,NONE,...,NaN,NaN,Visa,967030,721.0,3.455312e+10,3.273276e+10,37776721.0,4601.0,approved
56151,6989,1,Visa,558768,3280.00,2022-01-02T23:51:10-04:00,PAYMENT,2.706688e+10,ARS,NONE,...,NaN,NaN,Visa,987903,965.0,3.455312e+10,3.273276e+10,82341942.0,7786.0,approved

In [8]:
df['CARD_NUMBER'] = df['CARD_SIX_FIRST_DIGITS'].astype(str) + 'XXXXXX' + df['CARD_FOUR_LAST_DIGITS'].astype(str)

In [9]:
df

,CARD_FOUR_LAST_DIGITS,CARD_ISSUER_ID,CARD_ISSUER_NAME,CARD_SIX_FIRST_DIGITS,MOV_AMOUNT,MOV_CREATED_DATE,MOV_OPERATION,PAY_COLLECTOR_DOCUMENT,PAY_CURRENCY,PAY_MARKETPLACE,...,CAPTURE_MERCHANT_TRX_REFERENCE,PURCHASE_ACQUIRER,PURCHASE_AUTHORIZATION_CODE,PURCHASE_BATCH_ID,PURCHASE_GATEWAY_TRX_ID,PURCHASE_ID,PURCHASE_MERCHANT_NUMBER,PURCHASE_MERCHANT_TRX_REFERENCE,PURCHASE_STATUS,CARD_NUMBER
0,7978,1,Visa,588559,2600.00,2022-01-02T23:13:36-04:00,PAYMENT,2.021364e+10,ARS,NONE,...,NaN,Visa,932099,87.0,3.455300e+10,3.273268e+10,33106584.0,6059.0,approved,588559XXXXXX7978
1,7976,1,Visa,558766,1709.00,2022-01-02T23:13:35-04:00,PAYMENT,2.034094e+10,ARS,NONE,...,NaN,Visa,711990,550.0,3.455300e+10,3.273267e+10,32827909.0,5785.0,approved,558766XXXXXX7976
2,5979,1,Visa,569888,500.00,2022-01-02T23:13:37-04:00,PAYMENT,2.020107e+10,ARS,NONE,...,NaN,Visa,957843,83.0,3.455300e+10,3.273267e+10,33106584.0,6029.0,approved,569888XXXXXX5979
3,5977,12433,Visa Ahora,595978,129999.00,2022-01-02T23:12:39-04:00,PAYMENT,3.070881e+10,ARS,NONE,...,9921.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,595978XXXXXX5977
4,7896,316,BBVA,579555,4410.00,2022-01-02T23:12:38-04:00,PAYMENT,2.742115e+10,ARS,NONE,...,NaN,Visa,86,339.0,3.455300e+10,3.273268e+10,40326803.0,292.0,approved,579555XXXXXX7896
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56147,7896,1,Visa,558765,1163.99,2022-01-02T23:50:36-04:00,PAYMENT,3.071451e+10,ARS,MELI,...,NaN,Visa,37108,550.0,3.455311e+10,3.273276e+10,32827909.0,4914.0,approved,558765XXXXXX7896
56148,6668,279,Banco Galicia,566869,588.76,2022-01-02T23:51:39-04:00,PAYMENT,3.071531e+10,ARS,NONE,...,NaN,Visa,153,853.0,3.455311e+10,3.273275e+10,39725643.0,5099.0,approved,566869XXXXXX6668
56149,9977,1,Visa,558766,2290.00,2022-01-02T23:51:39-04:00,PAYMENT,2.027654e+10,ARS,NONE,...,NaN,Visa,723921,969.0,3.455311e+10,3.273276e+10,82341942.0,3379.0,approved,558766XXXXXX9977
56150,58,1,Visa,569888,131.10,2022-01-02T23:51:41-04:00,PAYMENT,2.723785e+10,ARS,NONE,...,NaN,Visa,967030,721.0,3.455312e+10,3.273276e+10,37776721.0,4601.0,approved,569888XXXXXX58
56151,6989,1,Visa,558768,3280.00,2022-01-02T23:51:10-04:00,PAYMENT,2.706688e+10,ARS,NONE,...,NaN,Visa,987903,965.0,3.455312e+10,3.273276e+10,82341942.0,7786.0,approved,558768XXXXXX6989

In [10]:
df['GTWC_AUTHORIZATION_CODE'] = np.where(
    (df['CAPTURE_AUTHORIZATION_CODE'] == '000000') & (df['CAPTURE_ACQUIRER'].str.lower() == 'cabal'),
    '',  # blank
    df['CAPTURE_AUTHORIZATION_CODE']
)

In [11]:
df

,CARD_FOUR_LAST_DIGITS,CARD_ISSUER_ID,CARD_ISSUER_NAME,CARD_SIX_FIRST_DIGITS,MOV_AMOUNT,MOV_CREATED_DATE,MOV_OPERATION,PAY_COLLECTOR_DOCUMENT,PAY_CURRENCY,PAY_MARKETPLACE,...,PURCHASE_ACQUIRER,PURCHASE_AUTHORIZATION_CODE,PURCHASE_BATCH_ID,PURCHASE_GATEWAY_TRX_ID,PURCHASE_ID,PURCHASE_MERCHANT_NUMBER,PURCHASE_MERCHANT_TRX_REFERENCE,PURCHASE_STATUS,CARD_NUMBER,GTWC_AUTHORIZATION_CODE
0,7978,1,Visa,588559,2600.00,2022-01-02T23:13:36-04:00,PAYMENT,2.021364e+10,ARS,NONE,...,Visa,932099,87.0,3.455300e+10,3.273268e+10,33106584.0,6059.0,approved,588559XXXXXX7978,NaN
1,7976,1,Visa,558766,1709.00,2022-01-02T23:13:35-04:00,PAYMENT,2.034094e+10,ARS,NONE,...,Visa,711990,550.0,3.455300e+10,3.273267e+10,32827909.0,5785.0,approved,558766XXXXXX7976,NaN
2,5979,1,Visa,569888,500.00,2022-01-02T23:13:37-04:00,PAYMENT,2.020107e+10,ARS,NONE,...,Visa,957843,83.0,3.455300e+10,3.273267e+10,33106584.0,6029.0,approved,569888XXXXXX5979,NaN
3,5977,12433,Visa Ahora,595978,129999.00,2022-01-02T23:12:39-04:00,PAYMENT,3.070881e+10,ARS,NONE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,595978XXXXXX5977,86
4,7896,316,BBVA,579555,4410.00,2022-01-02T23:12:38-04:00,PAYMENT,2.742115e+10,ARS,NONE,...,Visa,86,339.0,3.455300e+10,3.273268e+10,40326803.0,292.0,approved,579555XXXXXX7896,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56147,7896,1,Visa,558765,1163.99,2022-01-02T23:50:36-04:00,PAYMENT,3.071451e+10,ARS,MELI,...,Visa,37108,550.0,3.455311e+10,3.273276e+10,32827909.0,4914.0,approved,558765XXXXXX7896,NaN
56148,6668,279,Banco Galicia,566869,588.76,2022-01-02T23:51:39-04:00,PAYMENT,3.071531e+10,ARS,NONE,...,Visa,153,853.0,3.455311e+10,3.273275e+10,39725643.0,5099.0,approved,566869XXXXXX6668,NaN
56149,9977,1,Visa,558766,2290.00,2022-01-02T23:51:39-04:00,PAYMENT,2.027654e+10,ARS,NONE,...,Visa,723921,969.0,3.455311e+10,3.273276e+10,82341942.0,3379.0,approved,558766XXXXXX9977,NaN
56150,58,1,Visa,569888,131.10,2022-01-02T23:51:41-04:00,PAYMENT,2.723785e+10,ARS,NONE,...,Visa,967030,721.0,3.455312e+10,3.273276e+10,37776721.0,4601.0,approved,569888XXXXXX58,NaN
56151,6989,1,Visa,558768,3280.00,2022-01-02T23:51:10-04:00,PAYMENT,2.706688e+10,ARS,NONE,...,Visa,987903,965.0,3.455312e+10,3.273276e+10,82341942.0,7786.0,approved,558768XXXXXX6989,NaN

In [12]:
df.head(20)

,CARD_FOUR_LAST_DIGITS,CARD_ISSUER_ID,CARD_ISSUER_NAME,CARD_SIX_FIRST_DIGITS,MOV_AMOUNT,MOV_CREATED_DATE,MOV_OPERATION,PAY_COLLECTOR_DOCUMENT,PAY_CURRENCY,PAY_MARKETPLACE,...,PURCHASE_ACQUIRER,PURCHASE_AUTHORIZATION_CODE,PURCHASE_BATCH_ID,PURCHASE_GATEWAY_TRX_ID,PURCHASE_ID,PURCHASE_MERCHANT_NUMBER,PURCHASE_MERCHANT_TRX_REFERENCE,PURCHASE_STATUS,CARD_NUMBER,GTWC_AUTHORIZATION_CODE
0,7978,1,Visa,588559,2600.00,2022-01-02T23:13:36-04:00,PAYMENT,2.021364e+10,ARS,NONE,...,Visa,932099,87.0,3.455300e+10,3.273268e+10,33106584.0,6059.0,approved,588559XXXXXX7978,NaN
1,7976,1,Visa,558766,1709.00,2022-01-02T23:13:35-04:00,PAYMENT,2.034094e+10,ARS,NONE,...,Visa,711990,550.0,3.455300e+10,3.273267e+10,32827909.0,5785.0,approved,558766XXXXXX7976,NaN
2,5979,1,Visa,569888,500.00,2022-01-02T23:13:37-04:00,PAYMENT,2.020107e+10,ARS,NONE,...,Visa,957843,83.0,3.455300e+10,3.273267e+10,33106584.0,6029.0,approved,569888XXXXXX5979,NaN
3,5977,12433,Visa Ahora,595978,129999.00,2022-01-02T23:12:39-04:00,PAYMENT,3.070881e+10,ARS,NONE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,595978XXXXXX5977,86
4,7896,316,BBVA,579555,4410.00,2022-01-02T23:12:38-04:00,PAYMENT,2.742115e+10,ARS,NONE,...,Visa,86,339.0,3.455300e+10,3.273268e+10,40326803.0,292.0,approved,579555XXXXXX7896,NaN
5,6988,1,Visa,588897,120.00,2022-01-02T23:13:10-04:00,PAYMENT,2.793936e+10,ARS,NONE,...,Visa,980115,726.0,3.455300e+10,3.273267e+10,37017811.0,9999.0,approved,588897XXXXXX6988,NaN
6,9,3,Mastercard,598958,795.00,2022-01-02T23:13:08-04:00,PAYMENT,3.070703e+10,ARS,NONE,...,Visa,785464,852.0,3.455300e+10,3.273268e+10,51410900.0,4140.0,approved,598958XXXXXX9,NaN
7,8866,310,Banco Santander,559979,800.00,2022-01-02T23:13:40-04:00,PAYMENT,2.093560e+10,ARS,MELI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,559979XXXXXX8866,82
8,5998,1,Visa,558677,1460.00,2022-01-02T23:13:37-04:00,PAYMENT,2.029592e+10,ARS,NONE,...,Visa,964476,549.0,3.455300e+10,3.273268e+10,32827909.0,5227.0,approved,558677XXXXXX5998,NaN
9,8597,1,Visa,558765,640.00,2022-01-02T23:13:38-04:00,PAYMENT,2.736087e+10,ARS,NONE,...,Visa,867174,550.0,3.455300e+10,3.273267e+10,32827909.0,4818.0,approved,558765XXXXXX8597,NaN
10,7789,1,Visa,555979,3450.00,2022-01-02T23:13:09-04:00,PAYMENT,2.337599e+10,ARS,NONE,...,Visa,182101,971.0,3.455300e+10,3.273268e+10,82341942.0,1772.0,approved,555979XXXXXX7789,NaN
11,7988,1,Visa,588897,1273.20,2022-01-02T23:13:40-04:00,PAYMENT,3.070857e+10,ARS,NONE,...,Visa,996087,416.0,3.455300e+10,3.273268e+10,37017811.0,2447.0,approved,588897XXXXXX7988,NaN
12,7898,12468,Tarjeta Mercado Pago,555769,2300.00,2022-01-02T23:13:11-04:00,PAYMENT,2.336937e+10,ARS,NONE,...,Visa,266386,416.0,3.455300e+10,3.273267e+10,47838149.0,4202.0,approved,555769XXXXXX7898,NaN
13,8985,1,Visa,558677,800.00,2022-01-02T23:13:39-04:00,PAYMENT,2.017207e+10,ARS,NONE,...,Visa,961388,967.0,3.455300e+10,3.273268e+10,82341942.0,5608.0,approved,558677XXXXXX8985,NaN
14,6877,1,Visa,577956,1290.00,2022-01-02T23:13:12-04:00,PAYMENT,3.071653e+10,ARS,NONE,...,Visa,162753,116.0,3.455300e+10,3.273269e+10,37017811.0,1815.0,approved,577956XXXXXX6877,NaN
15,69,3,Mastercard,588779,883.84,2022-01-02T23:12:40-04:00,PAYMENT,3.065986e+10,ARS,NONE,...,Visa,989771,894.0,3.455300e+10,3.273269e+10,82336652.0,3071.0,approved,588779XXXXXX69,NaN
16,6986,1,Visa,558766,640.00,2022-01-02T23:12:40-04:00,PAYMENT,2.030237e+10,ARS,NONE,...,Visa,31006,226.0,3.455300e+10,3.273269e+10,32827909.0,2207.0,approved,558766XXXXXX6986,NaN
17,9976,1,Visa,558766,2460.00,2022-01-02T23:13:42-04:00,PAYMENT,2.737493e+10,ARS,NONE,...,Visa,180255,962.0,3.455300e+10,3.273268e+10,82341942.0,1232.0,approved,558766XXXXXX9976,NaN
18,6978,1,Visa,558758,4555.25,2022-01-02T23:13:41-04:00,PAYMENT,3.065986e+10,ARS,NONE,...,Visa,389740,315.0,3.455300e+10,3.273267e+10,37017811.0,2632.0,approved,558758XXXXXX6978,NaN
19,6759,1,Visa,558765,430.00,2022-01-02T23:13:39-04:00,PAYMENT,2.008012e+10,ARS,NONE,...,Visa,911686,969.0,3.455300e+10,3.273268e+10,82341942.0,3446.0,approved,558765XXXXXX6759,NaN

In [13]:
def get_acquirer(row):
    acq_fields = [row['CAPTURE_ACQUIRER'], row['PURCHASE_ACQUIRER'], row['AUTH_ACQUIRER']]
    all_acq = ' '.join([str(a).lower() for a in acq_fields if pd.notna(a)])

    if any(x in all_acq for x in ['mastercard', 'firstdata', 'diners']):
        return 'FD'
    elif 'visa' in all_acq:
        return 'PRISMA'
    else:
        return next((a.upper() for a in acq_fields if pd.notna(a)), '')

In [14]:
df['GTWT_ACQUIRER'] = df.apply(get_acquirer, axis=1)

In [15]:
df

,CARD_FOUR_LAST_DIGITS,CARD_ISSUER_ID,CARD_ISSUER_NAME,CARD_SIX_FIRST_DIGITS,MOV_AMOUNT,MOV_CREATED_DATE,MOV_OPERATION,PAY_COLLECTOR_DOCUMENT,PAY_CURRENCY,PAY_MARKETPLACE,...,PURCHASE_AUTHORIZATION_CODE,PURCHASE_BATCH_ID,PURCHASE_GATEWAY_TRX_ID,PURCHASE_ID,PURCHASE_MERCHANT_NUMBER,PURCHASE_MERCHANT_TRX_REFERENCE,PURCHASE_STATUS,CARD_NUMBER,GTWC_AUTHORIZATION_CODE,GTWT_ACQUIRER
0,7978,1,Visa,588559,2600.00,2022-01-02T23:13:36-04:00,PAYMENT,2.021364e+10,ARS,NONE,...,932099,87.0,3.455300e+10,3.273268e+10,33106584.0,6059.0,approved,588559XXXXXX7978,NaN,PRISMA
1,7976,1,Visa,558766,1709.00,2022-01-02T23:13:35-04:00,PAYMENT,2.034094e+10,ARS,NONE,...,711990,550.0,3.455300e+10,3.273267e+10,32827909.0,5785.0,approved,558766XXXXXX7976,NaN,PRISMA
2,5979,1,Visa,569888,500.00,2022-01-02T23:13:37-04:00,PAYMENT,2.020107e+10,ARS,NONE,...,957843,83.0,3.455300e+10,3.273267e+10,33106584.0,6029.0,approved,569888XXXXXX5979,NaN,PRISMA
3,5977,12433,Visa Ahora,595978,129999.00,2022-01-02T23:12:39-04:00,PAYMENT,3.070881e+10,ARS,NONE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,595978XXXXXX5977,86,PRISMA
4,7896,316,BBVA,579555,4410.00,2022-01-02T23:12:38-04:00,PAYMENT,2.742115e+10,ARS,NONE,...,86,339.0,3.455300e+10,3.273268e+10,40326803.0,292.0,approved,579555XXXXXX7896,NaN,PRISMA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56147,7896,1,Visa,558765,1163.99,2022-01-02T23:50:36-04:00,PAYMENT,3.071451e+10,ARS,MELI,...,37108,550.0,3.455311e+10,3.273276e+10,32827909.0,4914.0,approved,558765XXXXXX7896,NaN,PRISMA
56148,6668,279,Banco Galicia,566869,588.76,2022-01-02T23:51:39-04:00,PAYMENT,3.071531e+10,ARS,NONE,...,153,853.0,3.455311e+10,3.273275e+10,39725643.0,5099.0,approved,566869XXXXXX6668,NaN,PRISMA
56149,9977,1,Visa,558766,2290.00,2022-01-02T23:51:39-04:00,PAYMENT,2.027654e+10,ARS,NONE,...,723921,969.0,3.455311e+10,3.273276e+10,82341942.0,3379.0,approved,558766XXXXXX9977,NaN,PRISMA
56150,58,1,Visa,569888,131.10,2022-01-02T23:51:41-04:00,PAYMENT,2.723785e+10,ARS,NONE,...,967030,721.0,3.455312e+10,3.273276e+10,37776721.0,4601.0,approved,569888XXXXXX58,NaN,PRISMA
56151,6989,1,Visa,558768,3280.00,2022-01-02T23:51:10-04:00,PAYMENT,2.706688e+10,ARS,NONE,...,987903,965.0,3.455312e+10,3.273276e+10,82341942.0,7786.0,approved,558768XXXXXX6989,NaN,PRISMA

In [16]:
def infer_brand(row):
    pay_method = str(row['PAY_METHOD']).upper()
    if any(k in pay_method for k in ['MASTER', 'MAESTRO', 'MASTERCARD']):
        return 'MASTERCARD'
    num_prefix = str(row['CARD_SIX_FIRST_DIGITS'])[:2]
    if num_prefix in ['34', '37']:
        return 'AMERICAN EXPRESS'
    elif num_prefix.startswith('5') or num_prefix.startswith('2'):
        return 'MASTERCARD'
    elif num_prefix.startswith('4'):
        return 'VISA'
    else:
        return 'PENDENTE'

In [17]:
df['BRAND'] = df.apply(infer_brand, axis=1)

In [18]:
df

,CARD_FOUR_LAST_DIGITS,CARD_ISSUER_ID,CARD_ISSUER_NAME,CARD_SIX_FIRST_DIGITS,MOV_AMOUNT,MOV_CREATED_DATE,MOV_OPERATION,PAY_COLLECTOR_DOCUMENT,PAY_CURRENCY,PAY_MARKETPLACE,...,PURCHASE_BATCH_ID,PURCHASE_GATEWAY_TRX_ID,PURCHASE_ID,PURCHASE_MERCHANT_NUMBER,PURCHASE_MERCHANT_TRX_REFERENCE,PURCHASE_STATUS,CARD_NUMBER,GTWC_AUTHORIZATION_CODE,GTWT_ACQUIRER,BRAND
0,7978,1,Visa,588559,2600.00,2022-01-02T23:13:36-04:00,PAYMENT,2.021364e+10,ARS,NONE,...,87.0,3.455300e+10,3.273268e+10,33106584.0,6059.0,approved,588559XXXXXX7978,NaN,PRISMA,MASTERCARD
1,7976,1,Visa,558766,1709.00,2022-01-02T23:13:35-04:00,PAYMENT,2.034094e+10,ARS,NONE,...,550.0,3.455300e+10,3.273267e+10,32827909.0,5785.0,approved,558766XXXXXX7976,NaN,PRISMA,MASTERCARD
2,5979,1,Visa,569888,500.00,2022-01-02T23:13:37-04:00,PAYMENT,2.020107e+10,ARS,NONE,...,83.0,3.455300e+10,3.273267e+10,33106584.0,6029.0,approved,569888XXXXXX5979,NaN,PRISMA,MASTERCARD
3,5977,12433,Visa Ahora,595978,129999.00,2022-01-02T23:12:39-04:00,PAYMENT,3.070881e+10,ARS,NONE,...,NaN,NaN,NaN,NaN,NaN,NaN,595978XXXXXX5977,86,PRISMA,MASTERCARD
4,7896,316,BBVA,579555,4410.00,2022-01-02T23:12:38-04:00,PAYMENT,2.742115e+10,ARS,NONE,...,339.0,3.455300e+10,3.273268e+10,40326803.0,292.0,approved,579555XXXXXX7896,NaN,PRISMA,MASTERCARD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56147,7896,1,Visa,558765,1163.99,2022-01-02T23:50:36-04:00,PAYMENT,3.071451e+10,ARS,MELI,...,550.0,3.455311e+10,3.273276e+10,32827909.0,4914.0,approved,558765XXXXXX7896,NaN,PRISMA,MASTERCARD
56148,6668,279,Banco Galicia,566869,588.76,2022-01-02T23:51:39-04:00,PAYMENT,3.071531e+10,ARS,NONE,...,853.0,3.455311e+10,3.273275e+10,39725643.0,5099.0,approved,566869XXXXXX6668,NaN,PRISMA,MASTERCARD
56149,9977,1,Visa,558766,2290.00,2022-01-02T23:51:39-04:00,PAYMENT,2.027654e+10,ARS,NONE,...,969.0,3.455311e+10,3.273276e+10,82341942.0,3379.0,approved,558766XXXXXX9977,NaN,PRISMA,MASTERCARD
56150,58,1,Visa,569888,131.10,2022-01-02T23:51:41-04:00,PAYMENT,2.723785e+10,ARS,NONE,...,721.0,3.455312e+10,3.273276e+10,37776721.0,4601.0,approved,569888XXXXXX58,NaN,PRISMA,MASTERCARD
56151,6989,1,Visa,558768,3280.00,2022-01-02T23:51:10-04:00,PAYMENT,2.706688e+10,ARS,NONE,...,965.0,3.455312e+10,3.273276e+10,82341942.0,7786.0,approved,558768XXXXXX6989,NaN,PRISMA,MASTERCARD

In [19]:
def get_first_non_empty(row):
    for col in ['PURCHASE_MERCHANT_NUMBER', 'CAPTURE_MERCHANT_NUMBER', 'AUTH_MERCHANT_NUMBER']:
        if pd.notna(row[col]) and row[col] != '':
            return row[col]
    return ''

In [20]:
df['GTWT_MERCHANT_NUMBER'] = df.apply(get_first_non_empty, axis=1)

In [21]:
df

,CARD_FOUR_LAST_DIGITS,CARD_ISSUER_ID,CARD_ISSUER_NAME,CARD_SIX_FIRST_DIGITS,MOV_AMOUNT,MOV_CREATED_DATE,MOV_OPERATION,PAY_COLLECTOR_DOCUMENT,PAY_CURRENCY,PAY_MARKETPLACE,...,PURCHASE_GATEWAY_TRX_ID,PURCHASE_ID,PURCHASE_MERCHANT_NUMBER,PURCHASE_MERCHANT_TRX_REFERENCE,PURCHASE_STATUS,CARD_NUMBER,GTWC_AUTHORIZATION_CODE,GTWT_ACQUIRER,BRAND,GTWT_MERCHANT_NUMBER
0,7978,1,Visa,588559,2600.00,2022-01-02T23:13:36-04:00,PAYMENT,2.021364e+10,ARS,NONE,...,3.455300e+10,3.273268e+10,33106584.0,6059.0,approved,588559XXXXXX7978,NaN,PRISMA,MASTERCARD,33106584.0
1,7976,1,Visa,558766,1709.00,2022-01-02T23:13:35-04:00,PAYMENT,2.034094e+10,ARS,NONE,...,3.455300e+10,3.273267e+10,32827909.0,5785.0,approved,558766XXXXXX7976,NaN,PRISMA,MASTERCARD,32827909.0
2,5979,1,Visa,569888,500.00,2022-01-02T23:13:37-04:00,PAYMENT,2.020107e+10,ARS,NONE,...,3.455300e+10,3.273267e+10,33106584.0,6029.0,approved,569888XXXXXX5979,NaN,PRISMA,MASTERCARD,33106584.0
3,5977,12433,Visa Ahora,595978,129999.00,2022-01-02T23:12:39-04:00,PAYMENT,3.070881e+10,ARS,NONE,...,NaN,NaN,NaN,NaN,NaN,595978XXXXXX5977,86,PRISMA,MASTERCARD,48830723.0
4,7896,316,BBVA,579555,4410.00,2022-01-02T23:12:38-04:00,PAYMENT,2.742115e+10,ARS,NONE,...,3.455300e+10,3.273268e+10,40326803.0,292.0,approved,579555XXXXXX7896,NaN,PRISMA,MASTERCARD,40326803.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56147,7896,1,Visa,558765,1163.99,2022-01-02T23:50:36-04:00,PAYMENT,3.071451e+10,ARS,MELI,...,3.455311e+10,3.273276e+10,32827909.0,4914.0,approved,558765XXXXXX7896,NaN,PRISMA,MASTERCARD,32827909.0
56148,6668,279,Banco Galicia,566869,588.76,2022-01-02T23:51:39-04:00,PAYMENT,3.071531e+10,ARS,NONE,...,3.455311e+10,3.273275e+10,39725643.0,5099.0,approved,566869XXXXXX6668,NaN,PRISMA,MASTERCARD,39725643.0
56149,9977,1,Visa,558766,2290.00,2022-01-02T23:51:39-04:00,PAYMENT,2.027654e+10,ARS,NONE,...,3.455311e+10,3.273276e+10,82341942.0,3379.0,approved,558766XXXXXX9977,NaN,PRISMA,MASTERCARD,82341942.0
56150,58,1,Visa,569888,131.10,2022-01-02T23:51:41-04:00,PAYMENT,2.723785e+10,ARS,NONE,...,3.455312e+10,3.273276e+10,37776721.0,4601.0,approved,569888XXXXXX58,NaN,PRISMA,MASTERCARD,37776721.0
56151,6989,1,Visa,558768,3280.00,2022-01-02T23:51:10-04:00,PAYMENT,2.706688e+10,ARS,NONE,...,3.455312e+10,3.273276e+10,82341942.0,7786.0,approved,558768XXXXXX6989,NaN,PRISMA,MASTERCARD,82341942.0

In [22]:
df['MOV_CREATION_DATE'] = pd.to_datetime(df['MOV_CREATED_DATE'], errors='coerce') + pd.Timedelta(days=1)
df['MOV_CREATION_DATE'] = df['MOV_CREATION_DATE'].dt.date  # strip time part

In [23]:
df

,CARD_FOUR_LAST_DIGITS,CARD_ISSUER_ID,CARD_ISSUER_NAME,CARD_SIX_FIRST_DIGITS,MOV_AMOUNT,MOV_CREATED_DATE,MOV_OPERATION,PAY_COLLECTOR_DOCUMENT,PAY_CURRENCY,PAY_MARKETPLACE,...,PURCHASE_ID,PURCHASE_MERCHANT_NUMBER,PURCHASE_MERCHANT_TRX_REFERENCE,PURCHASE_STATUS,CARD_NUMBER,GTWC_AUTHORIZATION_CODE,GTWT_ACQUIRER,BRAND,GTWT_MERCHANT_NUMBER,MOV_CREATION_DATE
0,7978,1,Visa,588559,2600.00,2022-01-02T23:13:36-04:00,PAYMENT,2.021364e+10,ARS,NONE,...,3.273268e+10,33106584.0,6059.0,approved,588559XXXXXX7978,NaN,PRISMA,MASTERCARD,33106584.0,2022-01-03
1,7976,1,Visa,558766,1709.00,2022-01-02T23:13:35-04:00,PAYMENT,2.034094e+10,ARS,NONE,...,3.273267e+10,32827909.0,5785.0,approved,558766XXXXXX7976,NaN,PRISMA,MASTERCARD,32827909.0,2022-01-03
2,5979,1,Visa,569888,500.00,2022-01-02T23:13:37-04:00,PAYMENT,2.020107e+10,ARS,NONE,...,3.273267e+10,33106584.0,6029.0,approved,569888XXXXXX5979,NaN,PRISMA,MASTERCARD,33106584.0,2022-01-03
3,5977,12433,Visa Ahora,595978,129999.00,2022-01-02T23:12:39-04:00,PAYMENT,3.070881e+10,ARS,NONE,...,NaN,NaN,NaN,NaN,595978XXXXXX5977,86,PRISMA,MASTERCARD,48830723.0,2022-01-03
4,7896,316,BBVA,579555,4410.00,2022-01-02T23:12:38-04:00,PAYMENT,2.742115e+10,ARS,NONE,...,3.273268e+10,40326803.0,292.0,approved,579555XXXXXX7896,NaN,PRISMA,MASTERCARD,40326803.0,2022-01-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56147,7896,1,Visa,558765,1163.99,2022-01-02T23:50:36-04:00,PAYMENT,3.071451e+10,ARS,MELI,...,3.273276e+10,32827909.0,4914.0,approved,558765XXXXXX7896,NaN,PRISMA,MASTERCARD,32827909.0,2022-01-03
56148,6668,279,Banco Galicia,566869,588.76,2022-01-02T23:51:39-04:00,PAYMENT,3.071531e+10,ARS,NONE,...,3.273275e+10,39725643.0,5099.0,approved,566869XXXXXX6668,NaN,PRISMA,MASTERCARD,39725643.0,2022-01-03
56149,9977,1,Visa,558766,2290.00,2022-01-02T23:51:39-04:00,PAYMENT,2.027654e+10,ARS,NONE,...,3.273276e+10,82341942.0,3379.0,approved,558766XXXXXX9977,NaN,PRISMA,MASTERCARD,82341942.0,2022-01-03
56150,58,1,Visa,569888,131.10,2022-01-02T23:51:41-04:00,PAYMENT,2.723785e+10,ARS,NONE,...,3.273276e+10,37776721.0,4601.0,approved,569888XXXXXX58,NaN,PRISMA,MASTERCARD,37776721.0,2022-01-03
56151,6989,1,Visa,558768,3280.00,2022-01-02T23:51:10-04:00,PAYMENT,2.706688e+10,ARS,NONE,...,3.273276e+10,82341942.0,7786.0,approved,558768XXXXXX6989,NaN,PRISMA,MASTERCARD,82341942.0,2022-01-03

In [24]:
df.to_excel("DB_DOTA_Normalized.xlsx", index=False)